#! /bin/sh

## Del4y Config ##

# Disable DPMS and prevent screen from blanking
xset s off -dpms &

# Autostarting
pgrep -x sxhkd > /dev/null || sxhkd &

fc-cache -f &
picom -b --experimental-backends &
dunst &
$HOME/.config/polybar/launch.sh &
$HOME/.fehbg &
xrdb "$HOME/.Xresources" &


# bspwm stuff
workspaces() {
        name=1
        for monitor in `bspc query -M`; do
                bspc monitor ${monitor} -n "$name" -d '一' '二' '三' '四' '五' '六' '七'
                let name++
        done
}
workspaces

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Bspwm border color
bspc config focused_border_color "#6666CC"
bspc config normal_border_color "#333366"
bspc config active_border_color "#444b6a"
