#! /bin/sh

## Del4y Config ##

# Autostarting
pgrep -x sxhkd > /dev/null || sxhkd &

fc-cache -f &
picom -b --experimental-backends &
dunst &
~/.config/polybar/launch.sh &
~/.fehbg &
xrdb ~/.Xresources &


# Bspwm stuff
bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.57
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Bspwm border color
bspc config normal_border_color \#646D7E
bspc config focused_border_color \#5E81AC
